import type { ThemePresetId } from "../shared/protocol";

export type ResolvedTheme = "light" | "dark";

const themeTokenNames = [
  "--window",
  "--window-glass",
  "--sidebar",
  "--sidebar-glass",
  "--main",
  "--main-glass",
  "--surface",
  "--surface-glass",
  "--surface-muted",
  "--surface-muted-glass",
  "--line",
  "--line-glass",
  "--line-strong",
  "--line-strong-glass",
  "--text",
  "--text-strong",
  "--muted",
  "--muted-strong",
  "--muted-soft",
  "--muted-subtle",
  "--muted-icon",
  "--muted-path",
  "--muted-settings",
  "--accent",
  "--error",
  "--error-ink",
  "--surface-overlay",
  "--surface-overlay-hover",
  "--surface-overlay-border",
  "--surface-overlay-muted",
  "--theme-selection-bg",
  "--theme-selection-border",
  "--theme-selection-ink",
  "--theme-control-bg",
  "--theme-control-border",
  "--theme-control-hover-bg",
  "--theme-focus-ring",
  "--theme-code-bg",
  "--theme-code-border",
  "--theme-code-ink",
  "--theme-bubble-bg",
  "--theme-bubble-border",
  "--button-primary-bg",
  "--button-primary-border",
  "--button-primary-ink",
  "--button-primary-hover-bg",
  "--button-primary-hover-border",
  "--button-primary-disabled-bg",
  "--button-primary-disabled-border",
  "--button-primary-disabled-ink",
  "--hljs-keyword",
  "--hljs-built-in",
  "--hljs-type",
  "--hljs-string",
  "--hljs-number",
  "--hljs-literal",
  "--hljs-comment",
  "--hljs-regexp",
  "--hljs-meta",
  "--hljs-title",
  "--hljs-class",
  "--hljs-function",
  "--hljs-variable",
  "--hljs-params",
  "--hljs-attr",
  "--hljs-subst",
] as const;

type ThemeTokenName = (typeof themeTokenNames)[number];
type ThemeTokenMap = Partial<Record<ThemeTokenName, string>>;

export interface ThemePreset {
  readonly id: ThemePresetId;
  readonly name: string;
  readonly description: string;
  readonly swatches: readonly string[];
  readonly variants: Readonly<Record<ResolvedTheme, { readonly label: string; readonly tokens: ThemeTokenMap }>>;
}

const catppuccinLight = {
  "--window": "#e8e2f2",
  "--sidebar": "#ded5ed",
  "--main": "#f1ecf8",
  "--surface": "#fbf7ff",
  "--surface-muted": "#e6ddf2",
  "--line": "#c5b7dd",
  "--line-strong": "#ad99ca",
  "--text": "#4c4f69",
  "--text-strong": "#1e1e2e",
  "--muted": "#6c6f85",
  "--muted-strong": "#5c5f77",
  "--muted-soft": "#7c7f93",
  "--muted-subtle": "#8c8fa1",
  "--accent": "#8839ef",
  "--error": "#d20f39",
  "--error-ink": "#b0002a",
  "--theme-selection-bg": "#e8dcff",
  "--theme-selection-border": "#b994f0",
  "--theme-selection-ink": "#3f176f",
  "--theme-control-bg": "#f6eeff",
  "--theme-control-border": "#c4a3f3",
  "--theme-control-hover-bg": "#efe2ff",
  "--theme-focus-ring": "rgba(136, 57, 239, 0.28)",
  "--theme-code-bg": "#efe3ff",
  "--theme-code-border": "#c5a8f1",
  "--theme-code-ink": "#5b21a3",
  "--theme-bubble-bg": "#f8f1ff",
  "--theme-bubble-border": "#d3bdf4",
  "--button-primary-bg": "#8839ef",
  "--button-primary-border": "#8839ef",
  "--button-primary-ink": "#ffffff",
  "--button-primary-hover-bg": "#7287fd",
  "--button-primary-hover-border": "#7287fd",
} satisfies ThemeTokenMap;

const catppuccinDark = {
  "--window": "#11111b",
  "--sidebar": "#181825",
  "--main": "#1e1e2e",
  "--surface": "#313244",
  "--surface-muted": "#181825",
  "--line": "#45475a",
  "--line-strong": "#585b70",
  "--text": "#cdd6f4",
  "--text-strong": "#f5e0dc",
  "--muted": "#a6adc8",
  "--muted-strong": "#bac2de",
  "--muted-soft": "#9399b2",
  "--muted-subtle": "#7f849c",
  "--accent": "#cba6f7",
  "--error": "#f38ba8",
  "--error-ink": "#f38ba8",
  "--theme-selection-bg": "rgba(203, 166, 247, 0.14)",
  "--theme-selection-border": "rgba(203, 166, 247, 0.32)",
  "--theme-selection-ink": "#f5e0dc",
  "--theme-control-bg": "rgba(203, 166, 247, 0.08)",
  "--theme-control-border": "rgba(203, 166, 247, 0.24)",
  "--theme-control-hover-bg": "rgba(203, 166, 247, 0.12)",
  "--theme-focus-ring": "rgba(203, 166, 247, 0.22)",
  "--theme-code-bg": "rgba(203, 166, 247, 0.1)",
  "--theme-code-border": "rgba(203, 166, 247, 0.2)",
  "--theme-code-ink": "#f5e0dc",
  "--theme-bubble-bg": "rgba(203, 166, 247, 0.06)",
  "--theme-bubble-border": "rgba(203, 166, 247, 0.18)",
  "--button-primary-bg": "#cba6f7",
  "--button-primary-border": "#cba6f7",
  "--button-primary-ink": "#11111b",
  "--button-primary-hover-bg": "#b4befe",
  "--button-primary-hover-border": "#b4befe",
} satisfies ThemeTokenMap;

const tokyoLight = {
  ...catppuccinLight,
  "--window": "#e2e8f4",
  "--sidebar": "#d6deef",
  "--main": "#eef3fb",
  "--surface": "#f7faff",
  "--surface-muted": "#dfe7f6",
  "--line": "#b5c3dd",
  "--line-strong": "#94a7ca",
  "--text": "#343b58",
  "--text-strong": "#16161e",
  "--muted": "#565a6e",
  "--muted-strong": "#414868",
  "--muted-soft": "#787c99",
  "--accent": "#34548a",
  "--theme-selection-bg": "#dbe8ff",
  "--theme-selection-border": "#8cadde",
  "--theme-selection-ink": "#1f3764",
  "--theme-control-bg": "#f0f6ff",
  "--theme-control-border": "#98b7e5",
  "--theme-control-hover-bg": "#dfeaff",
  "--theme-focus-ring": "rgba(52, 84, 138, 0.28)",
  "--theme-code-bg": "#e4efff",
  "--theme-code-border": "#9dbce8",
  "--theme-code-ink": "#243b6b",
  "--theme-bubble-bg": "#f3f7ff",
  "--theme-bubble-border": "#b7cdf0",
  "--button-primary-bg": "#34548a",
  "--button-primary-border": "#34548a",
  "--button-primary-hover-bg": "#2e7de9",
  "--button-primary-hover-border": "#2e7de9",
} satisfies ThemeTokenMap;

const tokyoDark = {
  ...catppuccinDark,
  "--window": "#16161e",
  "--sidebar": "#1a1b26",
  "--main": "#1f2335",
  "--surface": "#24283b",
  "--surface-muted": "#1a1b26",
  "--line": "#3b4261",
  "--line-strong": "#414868",
  "--text": "#c0caf5",
  "--text-strong": "#f1f5ff",
  "--muted": "#a9b1d6",
  "--muted-strong": "#c0caf5",
  "--muted-soft": "#7aa2f7",
  "--muted-subtle": "#565f89",
  "--accent": "#7aa2f7",
  "--theme-selection-bg": "rgba(122, 162, 247, 0.14)",
  "--theme-selection-border": "rgba(122, 162, 247, 0.34)",
  "--theme-selection-ink": "#f1f5ff",
  "--theme-control-bg": "rgba(122, 162, 247, 0.08)",
  "--theme-control-border": "rgba(122, 162, 247, 0.26)",
  "--theme-control-hover-bg": "rgba(122, 162, 247, 0.12)",
  "--theme-focus-ring": "rgba(122, 162, 247, 0.22)",
  "--theme-code-bg": "rgba(122, 162, 247, 0.1)",
  "--theme-code-border": "rgba(122, 162, 247, 0.22)",
  "--theme-code-ink": "#c0caf5",
  "--theme-bubble-bg": "rgba(122, 162, 247, 0.06)",
  "--theme-bubble-border": "rgba(122, 162, 247, 0.18)",
  "--button-primary-bg": "#7aa2f7",
  "--button-primary-border": "#7aa2f7",
  "--button-primary-ink": "#16161e",
  "--button-primary-hover-bg": "#bb9af7",
  "--button-primary-hover-border": "#bb9af7",
} satisfies ThemeTokenMap;

const nordLight = {
  ...catppuccinLight,
  "--window": "#dce7f1",
  "--sidebar": "#d1deeb",
  "--main": "#eaf2f9",
  "--surface": "#f7fbff",
  "--surface-muted": "#dce8f3",
  "--line": "#aec1d4",
  "--line-strong": "#8fa8bf",
  "--text": "#3b4252",
  "--text-strong": "#2e3440",
  "--muted": "#5e687c",
  "--muted-strong": "#4c566a",
  "--accent": "#5e81ac",
  "--theme-selection-bg": "#d8ebf5",
  "--theme-selection-border": "#8ab1ca",
  "--theme-selection-ink": "#2f4d65",
  "--theme-control-bg": "#eef7fb",
  "--theme-control-border": "#98b9cf",
  "--theme-control-hover-bg": "#deedf5",
  "--theme-focus-ring": "rgba(94, 129, 172, 0.28)",
  "--theme-code-bg": "#e3f0f7",
  "--theme-code-border": "#a8c7d9",
  "--theme-code-ink": "#315f7c",
  "--theme-bubble-bg": "#f2f8fb",
  "--theme-bubble-border": "#b2ccd9",
  "--button-primary-bg": "#5e81ac",
  "--button-primary-border": "#5e81ac",
  "--button-primary-hover-bg": "#81a1c1",
  "--button-primary-hover-border": "#81a1c1",
} satisfies ThemeTokenMap;

const nordDark = {
  ...catppuccinDark,
  "--window": "#242933",
  "--sidebar": "#2e3440",
  "--main": "#2b303b",
  "--surface": "#3b4252",
  "--surface-muted": "#2e3440",
  "--line": "#4c566a",
  "--line-strong": "#5e687c",
  "--text": "#d8dee9",
  "--text-strong": "#eceff4",
  "--muted": "#aab4c4",
  "--muted-strong": "#c9d2e2",
  "--muted-soft": "#88c0d0",
  "--accent": "#88c0d0",
  "--theme-selection-bg": "rgba(136, 192, 208, 0.14)",
  "--theme-selection-border": "rgba(136, 192, 208, 0.32)",
  "--theme-selection-ink": "#eceff4",
  "--theme-control-bg": "rgba(136, 192, 208, 0.08)",
  "--theme-control-border": "rgba(136, 192, 208, 0.24)",
  "--theme-control-hover-bg": "rgba(136, 192, 208, 0.12)",
  "--theme-focus-ring": "rgba(136, 192, 208, 0.22)",
  "--theme-code-bg": "rgba(136, 192, 208, 0.1)",
  "--theme-code-border": "rgba(136, 192, 208, 0.22)",
  "--theme-code-ink": "#d8dee9",
  "--theme-bubble-bg": "rgba(136, 192, 208, 0.06)",
  "--button-primary-bg": "#88c0d0",
  "--button-primary-border": "#88c0d0",
  "--button-primary-ink": "#242933",
  "--button-primary-hover-bg": "#81a1c1",
  "--button-primary-hover-border": "#81a1c1",
} satisfies ThemeTokenMap;

// Palette from ayu-theme/vscode-ayu (MIT): https://github.com/ayu-theme/vscode-ayu
const ayuLight = {
  "--window": "#ebeef0",
  "--sidebar": "#f8f9fa",
  "--main": "#fcfcfc",
  "--surface": "#ffffff",
  "--surface-muted": "#fafafa",
  "--line": "#d5dce3",
  "--line-strong": "#c5ced8",
  "--text": "#5c6166",
  "--text-strong": "#3e4248",
  "--muted": "#828e9f",
  "--muted-strong": "#6c7787",
  "--muted-soft": "#9aa3b0",
  "--muted-subtle": "#adaeb1",
  "--accent": "#f29718",
  "--error": "#e65050",
  "--error-ink": "#c44040",
  "--theme-selection-bg": "#fff1d6",
  "--theme-selection-border": "#f2c572",
  "--theme-selection-ink": "#7e4b01",
  "--theme-control-bg": "#fff8ec",
  "--theme-control-border": "#f2c98a",
  "--theme-control-hover-bg": "#fff1d6",
  "--theme-focus-ring": "rgba(242, 151, 24, 0.28)",
  "--theme-code-bg": "#f4f5f6",
  "--theme-code-border": "#d5dce3",
  "--theme-code-ink": "#5c6166",
  "--theme-bubble-bg": "#fafafa",
  "--theme-bubble-border": "#e1e6eb",
  "--button-primary-bg": "#f29718",
  "--button-primary-border": "#f29718",
  "--button-primary-ink": "#7e4b01",
  "--button-primary-hover-bg": "#ea9216",
  "--button-primary-hover-border": "#ea9216",
  "--hljs-keyword": "#fa8532",
  "--hljs-built-in": "#55b4d4",
  "--hljs-type": "#22a4e6",
  "--hljs-string": "#86b300",
  "--hljs-number": "#a37acc",
  "--hljs-literal": "#a37acc",
  "--hljs-comment": "#adaeb1",
  "--hljs-regexp": "#4cbf99",
  "--hljs-meta": "#e59645",
  "--hljs-title": "#22a4e6",
  "--hljs-class": "#22a4e6",
  "--hljs-function": "#eba400",
  "--hljs-variable": "#f07171",
  "--hljs-params": "#a37acc",
  "--hljs-attr": "#eba400",
  "--hljs-subst": "#5c6166",
} satisfies ThemeTokenMap;

const ayuDark = {
  "--window": "#0d1017",
  "--sidebar": "#0d1017",
  "--main": "#10141c",
  "--surface": "#141821",
  "--surface-muted": "#0f131a",
  "--line": "#1b1f29",
  "--line-strong": "#2a3140",
  "--text": "#bfbdb6",
  "--text-strong": "#e6e1cf",
  "--muted": "#8b93a5",
  "--muted-strong": "#a8aebc",
  "--muted-soft": "#6b7385",
  "--muted-subtle": "#5a6673",
  "--accent": "#e6b450",
  "--error": "#d95757",
  "--error-ink": "#f06b73",
  "--theme-selection-bg": "rgba(230, 180, 80, 0.14)",
  "--theme-selection-border": "rgba(230, 180, 80, 0.32)",
  "--theme-selection-ink": "#e6e1cf",
  "--theme-control-bg": "rgba(230, 180, 80, 0.08)",
  "--theme-control-border": "rgba(230, 180, 80, 0.24)",
  "--theme-control-hover-bg": "rgba(230, 180, 80, 0.12)",
  "--theme-focus-ring": "rgba(230, 180, 80, 0.22)",
  "--theme-code-bg": "rgba(230, 180, 80, 0.1)",
  "--theme-code-border": "rgba(230, 180, 80, 0.2)",
  "--theme-code-ink": "#bfbdb6",
  "--theme-bubble-bg": "rgba(230, 180, 80, 0.06)",
  "--theme-bubble-border": "rgba(230, 180, 80, 0.18)",
  "--button-primary-bg": "#e6b450",
  "--button-primary-border": "#e6b450",
  "--button-primary-ink": "#0d1017",
  "--button-primary-hover-bg": "#deae4d",
  "--button-primary-hover-border": "#deae4d",
  "--hljs-keyword": "#ff8f40",
  "--hljs-built-in": "#39bae6",
  "--hljs-type": "#59c2ff",
  "--hljs-string": "#aad94c",
  "--hljs-number": "#d2a6ff",
  "--hljs-literal": "#d2a6ff",
  "--hljs-comment": "#5a6673",
  "--hljs-regexp": "#95e6cb",
  "--hljs-meta": "#e6c08a",
  "--hljs-title": "#59c2ff",
  "--hljs-class": "#59c2ff",
  "--hljs-function": "#ffb454",
  "--hljs-variable": "#f07178",
  "--hljs-params": "#d2a6ff",
  "--hljs-attr": "#ffb454",
  "--hljs-subst": "#bfbdb6",
} satisfies ThemeTokenMap;

function preset(
  id: ThemePresetId,
  name: string,
  description: string,
  swatches: readonly string[],
  light: ThemeTokenMap,
  dark: ThemeTokenMap,
): ThemePreset {
  return {
    id,
    name,
    description,
    swatches,
    variants: {
      light: { label: `${name} light`, tokens: light },
      dark: { label: `${name} dark`, tokens: dark },
    },
  };
}

export const themePresets: readonly ThemePreset[] = [
  {
    id: "default",
    name: "Default",
    description: "The current Grok Build palette, adapted from pi-gui.",
    swatches: ["#f8f8fb", "#ffffff", "#6a55f2", "#1f2638"],
    variants: {
      light: { label: "Default light", tokens: {} },
      dark: { label: "Default dark", tokens: {} },
    },
  },
  preset("catppuccin", "Catppuccin", "Soft pastel Latte and Mocha variants.", ["#eff1f5", "#1e1e2e", "#cba6f7", "#89b4fa"], catppuccinLight, catppuccinDark),
  preset("tokyo-night", "Tokyo Night", "A cool editor palette with a bright Day variant.", ["#d5d6db", "#1a1b26", "#7aa2f7", "#bb9af7"], tokyoLight, tokyoDark),
  preset("nord", "Nord", "Low-contrast arctic neutrals and blue accents.", ["#eceff4", "#2e3440", "#88c0d0", "#5e81ac"], nordLight, nordDark),
  preset("ayu", "Ayu", "Warm gold accents with Ayu Light and Dark from the VS Code theme.", ["#f8f9fa", "#0d1017", "#e6b450", "#59c2ff"], ayuLight, ayuDark),
];

export function applyThemePresetToRoot(root: HTMLElement, presetId: ThemePresetId, resolvedTheme: ResolvedTheme): void {
  for (const tokenName of themeTokenNames) {
    root.style.removeProperty(tokenName);
  }

  const next = themePresets.find((candidate) => candidate.id === presetId);
  if (!next || next.id === "default") {
    root.dataset.themePreset = "default";
    return;
  }

  root.dataset.themePreset = next.id;
  for (const [tokenName, value] of Object.entries(next.variants[resolvedTheme].tokens)) {
    root.style.setProperty(tokenName, value);
  }
}
